---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "monthly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    groups:
      pub:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/supabase/functions/_cmd"
    schedule:
      interval: "monthly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/landing"
    schedule:
      interval: "monthly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    groups:
      npm:
        patterns:
          - "*"
